---
- name: Eng.Faster Team Base Playbook
  hosts: vdi
  become: true
  
  tasks:
    
    - name: Print selected OS
      debug: msg="Selected OS -> {{ ansible_distribution }}"
        
    
    # Include the package list file for the target distribution
    - name: Include the distribution var file
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}-packages.yml"
        - "{{ ansible_distribution }}-packages.yml"
      
    # Install the packages available on the target distribution
    - name: Install distro available packages
      package:
        name: "{{ distro_packages }}"
        state: latest
    
    # Run distro specific tasks to more complex provisioning
    - name: Include Distro specific tasks
      include_tasks: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}-tasks.yml"
        - "{{ ansible_distribution }}-tasks.yml"
    
