---

  # Install the packages available
  - name: Install OS available packages
    win_chocolatey:
      name: "{{ item }}"
      state: present
    with_items:
        - git
        - googlechrome
        - nodejs
        - jdk8
        - gradle
        - intellijidea-community
        - maven
        - resharper-platform
